build-steps:
  -
    pipeline:
      type: script
      script:
        # Run composer install to get access the private acquia Pipelines tutorial repository with the secret.txt file
        - 'composer --no-interaction --quiet install'
        - 'cat vendor/acquia/buildstepstutorial/secret.txt'
        # In order to access the private repository you will need to use SSH keys configured in your Acquia github repo. Use the command pipeline help encrypt for instructions.
